id: P000008
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD96682
  title: བཀའ་འགྱུར། ༼དཔེ་བསྡུར་མ།）
  author: ''
  volumes:
    8dd97dfa11af44bdbbdbd58de7b877a9:
      image_group_id: I1PD96784
      title: ''
      volume_number: 1
      total_pages: 854
    03bae9d7f69449a0be68a3a2580d60c9:
      image_group_id: I1PD96785
      title: ''
      volume_number: 2
      total_pages: 894
    3f1cb4023e7e408bbe6cf68a0d019522:
      image_group_id: I1PD96786
      title: ''
      volume_number: 3
      total_pages: 846
    fe83289ef2c04f17aaea639b4a24e2fa:
      image_group_id: I1PD96787
      title: ''
      volume_number: 4
      total_pages: 866
    bc831dc2b9a04f76b1245405e59fea3c:
      image_group_id: I1PD96788
      title: ''
      volume_number: 5
      total_pages: 834
    c8f9fc5f3be44c15833cc89ffaa0321f:
      image_group_id: I1PD96789
      title: ''
      volume_number: 6
      total_pages: 810
    1ca80e48313441d2b46b939581600f52:
      image_group_id: I1PD96790
      title: ''
      volume_number: 7
      total_pages: 861
    08be1d7ac4034f9e9818f078792ae873:
      image_group_id: I1PD96791
      title: ''
      volume_number: 8
      total_pages: 761
    c5b0280b9ad8489094ecacc97b15b0ed:
      image_group_id: I1PD96792
      title: ''
      volume_number: 9
      total_pages: 934
    c5c496c7896e40888c20ecb2a75bebc1:
      image_group_id: I1PD96793
      title: ''
      volume_number: 10
      total_pages: 905
    b37925156f7f4e2eaf35a7c64b7d206c:
      image_group_id: I1PD96794
      title: ''
      volume_number: 11
      total_pages: 1005
    0dbf56383b9443b9b563f5dc843de018:
      image_group_id: I1PD96795
      title: ''
      volume_number: 12
      total_pages: 861
    73d85c1548034cf3899f06bee5bd570a:
      image_group_id: I1PD96796
      title: ''
      volume_number: 13
      total_pages: 986
    c2bf63a09b304bccb78c07085b787082:
      image_group_id: I1PD96797
      title: ''
      volume_number: 14
      total_pages: 908
    5bba8609f00d47ec903775d119b23ca2:
      image_group_id: I1PD96798
      title: ''
      volume_number: 15
      total_pages: 910
    84b09e4856ba4d398b215d828e5f9431:
      image_group_id: I1PD96799
      title: ''
      volume_number: 16
      total_pages: 913
    598ca86fc92945c1b49f2bf33793344f:
      image_group_id: I1PD96800
      title: ''
      volume_number: 17
      total_pages: 897
    5ec5164dd3f94f3ea342b2cc4f35482c:
      image_group_id: I1PD96801
      title: ''
      volume_number: 18
      total_pages: 924
    effc7d1a8e414934b8362d3720cd73d0:
      image_group_id: I1PD96802
      title: ''
      volume_number: 19
      total_pages: 912
    f08c03a72fbd4c49b5b695fc744f50c8:
      image_group_id: I1PD96803
      title: ''
      volume_number: 20
      total_pages: 892
    9ea82f1de8dd45468c2d15f80fa19a33:
      image_group_id: I1PD96804
      title: ''
      volume_number: 21
      total_pages: 892
    9f37e4bb649a4986ad30d2cded339703:
      image_group_id: I1PD96805
      title: ''
      volume_number: 22
      total_pages: 836
    26ad71e3df944aa39ab45231bad75178:
      image_group_id: I1PD96806
      title: ''
      volume_number: 23
      total_pages: 876
    b4be1b5c7a634acfa209132be6702cdc:
      image_group_id: I1PD96807
      title: ''
      volume_number: 24
      total_pages: 905
    b7b19cbcf64d4960b43fb9ee23844720:
      image_group_id: I1PD96808
      title: ''
      volume_number: 25
      total_pages: 932
    41403cb2e58342c09371804c97560a9f:
      image_group_id: I1PD96809
      title: ''
      volume_number: 26
      total_pages: 920
    ca80088671fb47e48330edc4c93fa93e:
      image_group_id: I1PD96810
      title: ''
      volume_number: 27
      total_pages: 960
    3ed0d3f6ef4d4935a021ff348f1ae115:
      image_group_id: I1PD96811
      title: ''
      volume_number: 28
      total_pages: 916
    da3b4e3501894f83be71d2cd298cf454:
      image_group_id: I1PD96812
      title: ''
      volume_number: 29
      total_pages: 780
    f5501daabca341c4a0543e6de57690f1:
      image_group_id: I1PD96813
      title: ''
      volume_number: 30
      total_pages: 805
    97ec76682501413fb1a5b69f873d10c1:
      image_group_id: I1PD96814
      title: ''
      volume_number: 31
      total_pages: 789
    f8758d254b41410cb593ceb1ada0c521:
      image_group_id: I1PD96815
      title: ''
      volume_number: 32
      total_pages: 788
    5a07c261c2364e27aa510dee59930095:
      image_group_id: I1PD96816
      title: ''
      volume_number: 33
      total_pages: 749
    98d06eabd2b2470dbc920d7d1f8fa8b1:
      image_group_id: I1PD96817
      title: ''
      volume_number: 34
      total_pages: 876
    3b340b249c4a41618796d4b0c5d90624:
      image_group_id: I1PD96818
      title: ''
      volume_number: 35
      total_pages: 1064
    c598835b04c346b196e30b2001e2b893:
      image_group_id: I1PD96819
      title: ''
      volume_number: 36
      total_pages: 1052
    2b47ee7fec27457eac238b5262a1386f:
      image_group_id: I1PD96820
      title: ''
      volume_number: 37
      total_pages: 1038
    68ccc126304a44eb89a514897bfaac8d:
      image_group_id: I1PD96821
      title: ''
      volume_number: 38
      total_pages: 984
    41bcdeca542744d89f4cf3bc73f92765:
      image_group_id: I1PD96822
      title: ''
      volume_number: 39
      total_pages: 822
    4d7b81f4cb9b4e0cbec1ae3a58bfaf63:
      image_group_id: I1PD96823
      title: ''
      volume_number: 40
      total_pages: 888
    7568c8e618e64dd88c5e27b8dc3862b9:
      image_group_id: I1PD96824
      title: ''
      volume_number: 41
      total_pages: 936
    9b4780d6a09546d9a9bd5ebc92083804:
      image_group_id: I1PD96825
      title: ''
      volume_number: 42
      total_pages: 893
    1a06fc1012c246d0b7b0562d5b20d669:
      image_group_id: I1PD96826
      title: ''
      volume_number: 43
      total_pages: 928
    1fa2e578e3074014b3f05eca05ab86c8:
      image_group_id: I1PD96827
      title: ''
      volume_number: 44
      total_pages: 870
    789983b936d944d2a17cdcb5aa991e73:
      image_group_id: I1PD96828
      title: ''
      volume_number: 45
      total_pages: 878
    9ee81892e1f444d8a3fbd4721d517c72:
      image_group_id: I1PD96829
      title: ''
      volume_number: 46
      total_pages: 785
    854e59986e5f487da2564b4d7d5dbfd0:
      image_group_id: I1PD96830
      title: ''
      volume_number: 47
      total_pages: 832
    e4e19b8c48c742f7abe986a86570829b:
      image_group_id: I1PD96831
      title: ''
      volume_number: 48
      total_pages: 778
    88addf41e33a43eab58a654e16523dea:
      image_group_id: I1PD96832
      title: ''
      volume_number: 49
      total_pages: 794
    722ea3667ad44c4c811357628f86af68:
      image_group_id: I1PD96833
      title: ''
      volume_number: 50
      total_pages: 802
    0459e508ee254f2b917541bc9d25a1a3:
      image_group_id: I1PD96834
      title: ''
      volume_number: 51
      total_pages: 810
    f3b1784ad4664c25ba0326ad439f9d27:
      image_group_id: I1PD96835
      title: ''
      volume_number: 52
      total_pages: 890
    cfcfae84264440ac904c3124035b2ae7:
      image_group_id: I1PD96836
      title: ''
      volume_number: 53
      total_pages: 890
    d07155c0133c425c9692b513f6c9ef94:
      image_group_id: I1PD96837
      title: ''
      volume_number: 54
      total_pages: 796
    c4bbb62d276e400ebb6505a24a75d9fc:
      image_group_id: I1PD96838
      title: ''
      volume_number: 55
      total_pages: 864
    cc072dbe9afb4bb98028162f2c090d4c:
      image_group_id: I1PD96839
      title: ''
      volume_number: 56
      total_pages: 856
    e15c154cd7be4aaa943194f4ec81388d:
      image_group_id: I1PD96840
      title: ''
      volume_number: 57
      total_pages: 940
    8f20c4d07400440eb7fba37c5af6a6ee:
      image_group_id: I1PD96841
      title: ''
      volume_number: 58
      total_pages: 860
    48fbfe9f70e044e882f62232e08533fb:
      image_group_id: I1PD96842
      title: ''
      volume_number: 59
      total_pages: 904
    364f01cf86f44cc38153d8a53ddb92b3:
      image_group_id: I1PD96843
      title: ''
      volume_number: 60
      total_pages: 822
    bf59c1c45d9143fcbc7be0ce5997f443:
      image_group_id: I1PD96844
      title: ''
      volume_number: 61
      total_pages: 872
    03011177e9df410cb8bbe5f071321e74:
      image_group_id: I1PD96845
      title: ''
      volume_number: 62
      total_pages: 856
    e25983d6d5f74e6e863a9e0e2fa23f28:
      image_group_id: I1PD96846
      title: ''
      volume_number: 63
      total_pages: 836
    1303ea3010564de08d588dda0bcf7cdc:
      image_group_id: I1PD96847
      title: ''
      volume_number: 64
      total_pages: 864
    3a7b0950242a45e0b4ce47ccf8bf4650:
      image_group_id: I1PD96848
      title: ''
      volume_number: 65
      total_pages: 828
    212533ff39c547b09d8a5ff36c2a7370:
      image_group_id: I1PD96849
      title: ''
      volume_number: 66
      total_pages: 892
    321eec8a8a634ac4a6e63f61f4dd30db:
      image_group_id: I1PD96850
      title: ''
      volume_number: 67
      total_pages: 882
    6f955461d62e41ef84535b1aaff4c6fa:
      image_group_id: I1PD96851
      title: ''
      volume_number: 68
      total_pages: 870
    47c292762a7042389c60b0e85c126774:
      image_group_id: I1PD96852
      title: ''
      volume_number: 69
      total_pages: 838
    4252f57c0a844c85b658525c7d88b892:
      image_group_id: I1PD96853
      title: ''
      volume_number: 70
      total_pages: 854
    381596fc1b3d49929a9cde3c646b5b0a:
      image_group_id: I1PD96854
      title: ''
      volume_number: 71
      total_pages: 858
    00026cc739b54e3fb1f33f0a0ecceec3:
      image_group_id: I1PD96855
      title: ''
      volume_number: 72
      total_pages: 978
    942a2094a3f94260ac67f89ba91f105f:
      image_group_id: I1PD96856
      title: ''
      volume_number: 73
      total_pages: 862
    a3b551ea64844b949cc5dad27125fcd7:
      image_group_id: I1PD96857
      title: ''
      volume_number: 74
      total_pages: 1028
    94847e7d6c9f465288d7756133540acc:
      image_group_id: I1PD96858
      title: ''
      volume_number: 75
      total_pages: 804
    890bdebf3ca54404aed02c0f5a5e1a12:
      image_group_id: I1PD96859
      title: ''
      volume_number: 76
      total_pages: 906
    28bc2565171644af855afc50999da564:
      image_group_id: I1PD96860
      title: ''
      volume_number: 77
      total_pages: 1126
    2e6cbb47505a45aeb4de8acb80caeeb9:
      image_group_id: I1PD96861
      title: ''
      volume_number: 78
      total_pages: 948
    e525650c0f334490834631251b5d2bf7:
      image_group_id: I1PD96862
      title: ''
      volume_number: 79
      total_pages: 929
    b249b5ed09d14ac28bf894180f9f8ab7:
      image_group_id: I1PD96863
      title: ''
      volume_number: 80
      total_pages: 1048
    59c2073016f6486da2e1f4eb2798da77:
      image_group_id: I1PD96864
      title: ''
      volume_number: 81
      total_pages: 1069
    312a47f4a6c346fb8485e617be70b71b:
      image_group_id: I1PD96865
      title: ''
      volume_number: 82
      total_pages: 854
    93899cc2f420445081ad488377077652:
      image_group_id: I1PD96866
      title: ''
      volume_number: 83
      total_pages: 1132
    8a91eeab834442e9a818a697a4e3f2ee:
      image_group_id: I1PD96867
      title: ''
      volume_number: 84
      total_pages: 824
    4bf6185667ec43eb90a5bf66f3b03f49:
      image_group_id: I1PD96868
      title: ''
      volume_number: 85
      total_pages: 854
    5d90e5d7a50e44edb3cf9b4a121fb12e:
      image_group_id: I1PD96869
      title: ''
      volume_number: 86
      total_pages: 964
    b8c4ec1f2dfc4575b02c62d40eefc543:
      image_group_id: I1PD96870
      title: ''
      volume_number: 87
      total_pages: 933
    d671d3aeb37b4386a2cc17bcde16799b:
      image_group_id: I1PD96871
      title: ''
      volume_number: 88
      total_pages: 1084
    82a2db0540774f2a83650a0ec52a1aba:
      image_group_id: I1PD96872
      title: ''
      volume_number: 89
      total_pages: 824
    28fef44d117045f48cd13d920895f248:
      image_group_id: I1PD96873
      title: ''
      volume_number: 90
      total_pages: 981
    4a585fd3a797491bbf957acf18e46efb:
      image_group_id: I1PD96874
      title: ''
      volume_number: 91
      total_pages: 1084
    b191c710e1f0430cb25cc68bc55a62c2:
      image_group_id: I1PD96875
      title: ''
      volume_number: 92
      total_pages: 954
    f3b2954798084060b92ed2cc2aa0238b:
      image_group_id: I1PD96876
      title: ''
      volume_number: 93
      total_pages: 918
    659792775cba4f4cbbc82124dd96e64b:
      image_group_id: I1PD96877
      title: ''
      volume_number: 94
      total_pages: 790
    39a45cc41d3247ddade0db65d9f01cec:
      image_group_id: I1PD96878
      title: ''
      volume_number: 95
      total_pages: 902
    be908c9339d7452298e09a797af0172d:
      image_group_id: I1PD96879
      title: ''
      volume_number: 96
      total_pages: 930
    43a05fec3c5844dbafa7b9f7e11a533c:
      image_group_id: I1PD96880
      title: ''
      volume_number: 97
      total_pages: 932
    a719a8e5f53c4841a15eebdbcf2e917a:
      image_group_id: I1PD96881
      title: ''
      volume_number: 98
      total_pages: 1032
    55807e4b37a94431b600120e7b440faf:
      image_group_id: I1PD96882
      title: ''
      volume_number: 99
      total_pages: 868
    131ac37fd810430c8631b64b0fd21f21:
      image_group_id: I1PD96883
      title: ''
      volume_number: 100
      total_pages: 620
    65f5c695e3904d678bb60874da5efe21:
      image_group_id: I1PD96884
      title: ''
      volume_number: 101
      total_pages: 966
    19fc609245654daf93366721104dcc28:
      image_group_id: I1PD96885
      title: ''
      volume_number: 102
      total_pages: 884
    4cbd9de39fb643d595ca9395ef2875d9:
      image_group_id: I1PD96886
      title: ''
      volume_number: 103
      total_pages: 868
    f3228f76ef2e46f89d5542b48db00c02:
      image_group_id: I1PD96887
      title: ''
      volume_number: 104
      total_pages: 992
    aad40a444ddf4777b9a13c8b943bffaa:
      image_group_id: I1PD96888
      title: ''
      volume_number: 105
      total_pages: 626
    80004f513c8b4713946efb0f1ea40a36:
      image_group_id: I1PD96889
      title: ''
      volume_number: 106
      total_pages: 660
    eb5843c7d5e64d7684b255ac629c2a11:
      image_group_id: I1PD96890
      title: ''
      volume_number: 107
      total_pages: 860
    11c68c2d7ebd4e63aaf736a56568cb6f:
      image_group_id: I1PD96891
      title: ''
      volume_number: 108
      total_pages: 812
    65a1412a2b334070af33eb7b7be61599:
      image_group_id: I4JW159
      title: ''
      volume_number: 109
      total_pages: 34
